### ISSUE TITLE
Verify correctness of Regula Falsi method in RootSolvers

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/CLIMA#101]
It seems that the Regula Falsi method tests are brittle for the CUDA tests (which operate at lower precision by default). Recording this here in case we are to use this method.

**Comment by simonbyrne** [comment]
The problem seems to be caused by two things:
1) The starting points aren't on either side of the root.
2) This line:
https://github.com/climate-machine/CLIMA/blob/9f93ecad302116870dc58ffaff4bd8e6eac8bd38/src/Utilities/src/RootSolvers.jl#L150
can exhibit catastrophic cancellation when `fb >> fa`, in which case it will simply keep setting `c = a`, without the interval getting smaller.

**Comment by charleskawczynski** [comment]
Closed by #117
