### ISSUE TITLE
Accessing grid.elemtoelem

### ISSUE THREAD

**Issue by asraero** [climate-machine/CLIMA#207]
What's the correct way to access the element to element mapping (`elemtoelem`) and the `elems` from the VanillaDiscretizations.jl file ? The docs suggest that this would be through `grid.elemtoelem` (similar to `grid.elemtobndy`) but this does not work ; it's instead accessible via `topology.elemtoelem`. @jkozdon @lcw

**Comment by jkozdon** [comment]
Stuff that is copied from topology to grid is stuff that we need in the kernels, since these will eventually by arrays that are copied to the GPU.

You should not need `elemtoelem` in the kernel since all this info is contained in `vmapM` and `vmapP`. You can see how this can be extracted bin the [`facerhs!`](https://github.com/climate-machine/CLIMA/blob/1349224152681a1b3b1d3e38a4bf3a8c4eee0b76/src/Atmos/Dycore/src/VanillaAtmosDiscretizations_kernels.jl#L896-L898)
