### ISSUE TITLE
Bug in the brick builder

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#290]
The brick mesh generator breaks when the values for `xmin, xmax` or `ymin, ymax` are negative and the grid warping function is used. For example:
xmin = -1000
xmax = -1

**Comment by jkozdon** [comment]
Can you give a minimal working example.

**Comment by jkozdon** [comment]
https://en.wikipedia.org/wiki/Minimal_working_example

**Comment by smarras79** [comment]
> Can you give a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example)
Sure. @jkozdon 

Pushed to: https://github.com/smarras79/CLIMA/blob/sm79/topography/test/DGmethods/compressible_Navier_Stokes/MWE_issue290.jl

See wrong vs correct output in Slack at https://climate-machine.slack.com/archives/CKZQQTGLU/p1561828806000400

**Comment by simonbyrne** [comment]
maybe upload to gist.github.com since Slack isn't as accessible?

**Comment by smarras79** [comment]
> maybe upload to gist.github.com since Slack isn't as accessible?

hi @simonbyrne  gist does not let me uplaod images. If you are logged into slack, you will be able to open the link though.

**Comment by jkozdon** [comment]
To my eyes it seems that it is the warping being used function not the brick mesh generator that is broken.

On Jun 29, 2019, at 11:11 AM, smarras79 <notifications@github.com<mailto:notifications@github.com>> wrote:


maybe upload to gist.github.com<http://gist.github.com> since Slack isn't as accessible?

hi @simonbyrne<https://github.com/simonbyrne> gist does not let me uplaod images. If you are logged into slack, you will be able to open the link though.

**Comment by jkozdon** [comment]
My guess would be that line 637 is should use `zmax` or `abs(xmax)` or something to calculate `a_c`

On Jun 29, 2019, at 12:36 PM, Jeremy Edward Kozdon <jekozdon@nps.edu<mailto:jekozdon@nps.edu>> wrote:

To my eyes it seems that it is the warping being used function not the brick mesh generator that is broken.

On Jun 29, 2019, at 11:11 AM, smarras79 <notifications@github.com<mailto:notifications@github.com>> wrote:


maybe upload to gist.github.com<http://gist.github.com/> since Slack isn't as accessible?

hi @simonbyrne<https://github.com/simonbyrne> gist does not let me uplaod images. If you are logged into slack, you will be able to open the link though.

**Comment by jkozdon** [comment]
You also probably do not want to build the spline every time you call this function, that is going to be super inefficient (https://github.com/smarras79/CLIMA/blob/85ac9b35cf63ae9a2252c16264d067357abd9894/test/DGmethods/compressible_Navier_Stokes/MWE_issue290.jl#L587-L591). Build it once then pass it in as an argument.

On Jun 29, 2019, at 12:38 PM, Jeremy Edward Kozdon <jekozdon@nps.edu<mailto:jekozdon@nps.edu>> wrote:

My guess would be that line 637 is should use `zmax` or `abs(xmax)` or something to calculate `a_c`

On Jun 29, 2019, at 12:36 PM, Jeremy Edward Kozdon <jekozdon@nps.edu<mailto:jekozdon@nps.edu>> wrote:

To my eyes it seems that it is the warping being used function not the brick mesh generator that is broken.

On Jun 29, 2019, at 11:11 AM, smarras79 <notifications@github.com<mailto:notifications@github.com>> wrote:


maybe upload to gist.github.com<http://gist.github.com/> since Slack isn't as accessible?

hi @simonbyrne<https://github.com/simonbyrne> gist does not let me uplaod images. If you are logged into slack, you will be able to open the link though.

**Comment by smarras79** [comment]
> To my eyes it seems that it is the warping being used function not the brick mesh generator that is broken.

It may be, but I am not 100% certain that is the case because the same issue occurs with both a warp function with analytic definition of topography and with a function that doesn't calculate anything but simply reads the file in.

**Comment by smarras79** [comment]
> You also probably do not want to build the spline every time you call this function, that is going to be super inefficient (https://github.com/smarras79/CLIMA/blob/85ac9b35cf63ae9a2252c16264d067357abd9894/test/DGmethods/compressible_Navier_Stokes/MWE_issue290.jl#L587-L591). Build it once then pass it in as an argument.

Yes, the inefficient use of spline1d  has already been solved by @lcw last week in its own driver. The current driver of this PR is just meant to test the topography reader regardless of anything else.

**Comment by smarras79** [comment]
> My guess would be that line 637 is should use `zmax` or `abs(xmax)` or something to calculate `a_c`

good catch. It should be abs(xmax).

**Comment by jkozdon** [comment]
Is this still an issue?

**Comment by smarras79** [comment]
> Is this still an issue?

As of now it is.

**Comment by jkozdon** [comment]
OK. Just wasn't sure if you forgot to close it.
