### ISSUE TITLE
`SVector`, `StructOfArrays`, etc...

### ISSUE THREAD

**Issue by jkozdon** [climate-machine/CLIMA#45]
Look to using [`SVector`](https://github.com/JuliaArrays/StaticArrays.jl), CuArray compatible [`StructOfArrays`](https://github.com/JuliaArrays/StructsOfArrays.jl), etc.. to improve readability of kernels; see also [`esderiv.jl`](https://github.com/jkozdon/nps_julialab_2019_Jan/blob/master/esderiv.jl) scratch file.

**Comment by peterahrens** [comment]
For newcomers to this issue, the idea is as follows:
Say we're using a really simple time stepper to update the velocity of the particles stored in a vector `v`. To start out, we could initialize the vector `v` as:
```
v = zeros(Float64, 3, nparticles)
dvdt = rand(3,3)
dt = 0.5
```
Then the time stepper could be written as:
```
for i in eachindex(v)
  v[1, i] += dvdt[1] #X coordinate of velocity
  v[2, i] += dvdt[2] #Y coordinate of velocity
  v[3, i] += dvdt[3] #Z coordinate of velocity
end
```
We could collapse this with another for-loop like 
```
for i in eachindex(v)
  for pos in 1:3
  v[pos, i] += dvdt[pos] #X coordinate of velocity
end
```
but in Julia, we can do better. Suppose instead we initialize our array of velocities as precisely that: an array of velocity vectors. Note that we are using SVectors so the compiler will make our tiny loops unroll and be fast.
We would initialize as
```
using StaticArrays
v = zeros(SVector{3, Float64}, 3, nparticles)
dvdt = SVector{3, Float64}(rand(3))
dt = 0.5
```
Then we can write our loop as 
```
for i in eachindex(v)
  v[i] += dvdt * dt #forward euler step of velocity
end
```
This works because `+` is defined on two vector types and `*` is defined between scalar and vector types! Way cool!

**Comment by lcw** [comment]
Right now we are waiting for https://github.com/JuliaGPU/CUDAnative.jl/issues/340 before we can start creating device arrays.
