### ISSUE TITLE
Boundary conditions

### ISSUE THREAD

**Issue by simonbyrne** [climate-machine/CLIMA#503]
One issue that has come up from discussions with @blallen, @asraero and @charleskawczynski is that we need a better way to handle boundary conditions.

- Consistent nomenclature and definitions
- How to specify boundary conditions for individual variables?
  - How should the boundary conditions for variables interact?
  - Can this be done consistently for both Ocean and Atmos models?
- How numerical fluxes interact with boundary conditions

Unfortunately this is something I don't really understand, so would be good to see more examples.

**Comment by blallen** [comment]
My proposed way of handling this is to have the user specify the variable, the type of boundary condition, and the value desired on the boundary. These variable by variable boundary are then grouped together into a set of boundary conditions that are specified along each physical boundary.

For example, for a generic Ocean model we can have three types of physical boundaries: Coastline, OceanFloor, and OceanSurface. These are types that exist for dispatching on the type of boundary condition: e.g.

```julia
abstract type OceanBoundaryCondition end
struct Coastline    <: OceanBoundaryCondition end
struct OceanFloor   <: OceanBoundaryCondition end
struct OceanSurface <: OceanBoundaryCondition end
```

Currently, I'm just using an if statement with the `bctype` parameter from the topology to determine when to dispatch to each set of BCs:

```julia
@inline function ocean_boundary_state!(m::HBModel, bctype, x...)
  if bctype == 1
    ocean_boundary_state!(m, Coastline(), x...)
  elseif bctype == 2
    ocean_boundary_state!(m, OceanFloor(), x...)
  elseif bctype == 3
    ocean_boundary_state!(m, OceanSurface(), x...)
  end
end
```

In the current code, this then goes to the existing BC infrastructure which dispatches based on the type of numerical flux with the user specifying the appropriate ghost-point value for each type of flux. I'd like to replace this with something like the following:

```julia
function ocean_boundary_state!(::HBModel, ::Coastline, x...)
  BC_dirichlet(u, f(state, aux, coords), ::Rusanov)
  BC_neumann(θ, g(state, aux, diff, coords), ::Upwind)
end
```

Basically, we have two functions that specify Dirichlet and Neumann boundary conditions for a given variable AND the type of numerical flux to use for that variable. The arguments of these functions are the variable you want to specify the boundary condition of, a function specifying the value of the variable (for dirichlet) or the derivative in the normal direction (for neumann), and the type of flux that should be used to compute necessary ghost-point value. 

For instance, currently if the user wants to specify the boundary value for a variable with a `::Rusanov` flux, they have to subtract off the minus side value and add twice the desired value because the numerical flux is computed as `f° = 0.5 * (f⁺ + f⁻) + C * (Q⁻ - Q⁺)`. For example, to say I want the value of `θ` to be 25 along a certain boundary, I currently have to write `state⁺.θ = -state⁻.θ + 2 * 25` in order to get the correct flux. In the proposed syntax, you would just type `BC_dirichlet(θ, 25, ::Rusanov)` and the trickery with the numerical flux would be handled automatically. 

This way the user can just read an equation set and specify the appropriate boundary conditions for each variable. Then they can group the different types of BCs on each variable as they please into their own BC types such as ::NoFlux, ::NoSlip, ::NoPenetration, etc. as the meaning of these changes for each problem.

**Comment by glwagner** [comment]
I'd like to add to Brandon's comment to provide some even-higher-level perspective from how boundary conditions are specified in `Oceananigans.jl`.

The geometric situation is a little different, so those details will differ in `CLIMA`. But for our purposes you can understand that we impose boundary conditions in a two-dimensional plane (of which there are 6 for each 6 faces of `Oceananigans.jl`'s rectangular domain).

A boundary condition is

```julia
struct BoundaryCondition{T, C}
    condition :: C
end
```

where `T` gives information about the 'type' of boundary condition. We offer finite volume implementations of four types of boundary condition at the moment:

* `Flux`: set the flux normal to the boundary (oriented in the positive direction of the coordinate system)
* `Gradient`: set the gradient normal to the boundary (otherwise known as "Neumann")
* `Value`: set the value of a field on the boundary (otherwise known as "Dirichlet")
* `NoPenetration`: specify no flow through the boundary.

`NoPenetration` is actually a special case of `Value` --- we need both because of our staggered grid. I'm not sure the same is necessary in DG.

In addition to the type of the boundary condition, the user also specifies the "condition", which has type `C`. We allow this to be a constant, array, or function with a specific, "low-level" functional form. 

Setting a no slip condition would look like

```julia
u_bottom_bc = BoundaryCondition(Value, 0)
```

or a temperature flux
```julia
θ_bottom_bc = BoundaryCondition(Flux, 1e-1)
```

We are also implementing wrapper types around functions that allow users to specify a "simple" boundary condition functions that do not require the full low-level syntax assumed by our boundary condition implementation, eg something like

```julia
temperature_oscillations(x, y, t) = cos(x) * sin(t)
temperature_bc = BoundaryCondition(Value, BoundaryFunction(temperature_oscillations))
```

(the syntax is slightly different due to details of the staggered grid). The wrapper `BoundaryFunction` can then be called with the low-level functionality syntax assumed by our boundary condition implementation, translating the user-defined function `bottom_temperature(x, y, t)` into this form.

We also provide constructors with convenient defaults; for example to build a set of 6 boundary conditions for temperature in a horizontally-periodic domain the user may write

```julia
θ_bcs = HorizontallyPeriodicBCs(top = BoundaryCondition(Flux, 1e-1),
                                bottom = BoundaryCondition(Gradient, dθdz))
```

Hope that helps.
